# Generated by Django 3.1.3 on 2021-07-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas',
        ),
    ]
