# Generated by Django 3.1.3 on 2021-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_remove_siswa_kelas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kelas',
        ),
    ]
