# Generated by Django 3.1.3 on 2021-08-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_delete_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('Kelas A', 'Kelas A'), ('Kelas B', 'Kelas B')], max_length=200, null=True)),
                ('semester', models.CharField(choices=[('GANJIL', 'GANJIL'), ('GENAP', 'GENAP')], max_length=200, null=True)),
                ('tahun_ajaran', models.CharField(blank=True, max_length=200, null=True)),
                ('mapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.mapel')),
                ('rincian_nilai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.rinciannilai')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.siswa')),
            ],
        ),
    ]
