# Generated by Django 3.1.3 on 2021-08-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_nilai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'verbose_name_plural': 'Nilai'},
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='kelas',
        ),
        migrations.AddField(
            model_name='nilai',
            name='kelompok',
            field=models.CharField(choices=[('Kelompok A', 'Kelompok A'), ('Kelompok B', 'Kelompok B')], max_length=200, null=True),
        ),
    ]
