# Generated by Django 3.1.2 on 2021-09-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_auto_20210812_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='rinciannilai',
            name='nama_mapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital.mapel'),
        ),
    ]
